//! # HTTP Request
//!
//! The request-side of the HTTP pipeline. Holds the [`HttpRequest`] type
//! (the per-connection context passed into handlers), pluggable protocol
//! parsers, and the supporting error and variable types.

mod http_parse_error;
mod http_parser_v1;
mod http_request_meta;
mod http_request_meta_parser;
mod parsers;
mod request_error;
mod variables;

use std::{collections::HashMap, net::SocketAddr, sync::Arc};

pub use http_request_meta::HttpRequestMeta;
pub use parsers::Parsers;
pub use request_error::RequestError;
use smol::{lock::RwLock, net::TcpStream};
pub use variables::Variables;

pub use http_request_meta_parser::HttpRequestMetaParser;

use crate::{
    router::{Node, Router},
    web::http_request::http_parse_error::HttpParseError,
};

/// # HttpRequest
///
/// Per-connection request context passed into every middleware and request
/// handler. Holds the peer socket, the underlying TCP stream, the parsed
/// request metadata, the resolved router node, and any request-scoped
/// variables (captured route parameters and user-set trace values).
pub struct HttpRequest<'app> {
    socket: SocketAddr,
    stream: Arc<RwLock<TcpStream>>,
    variables: Variables,
    meta: HttpRequestMeta,
    node: Arc<RwLock<Node<'app>>>,
}

unsafe impl<'app> Send for HttpRequest<'app> {}
unsafe impl<'app> Sync for HttpRequest<'app> {}

/// Generates a pair of accessors for a field: an immutable borrow
/// (`$get_name`) and a mutable borrow (`$get_mut_name`).
macro_rules! immut_mut_var {
    ($get_name:ident, $get_mut_name:ident, $field_name:ident, $ty:ty) => {
        pub fn $get_name(&self) -> &$ty {
            &self.$field_name
        }

        pub fn $get_mut_name(&mut self) -> &mut $ty {
            &mut self.$field_name
        }
    };
}

/// Generates a single immutable borrow accessor for a field.
macro_rules! immut_var {
    ($get_name:ident, $field_name:ident, $ty:ty) => {
        pub fn $get_name(&self) -> &$ty {
            &self.$field_name
        }
    };
}

impl<'app> HttpRequest<'app> {
    /// # Parse
    ///
    /// Parses the TcpStream and creates an HttpRequest.
    pub async fn parse(
        parser: &Parsers,
        router: Arc<RwLock<Router<'app>>>,
        stream: Arc<RwLock<TcpStream>>,
        socket: SocketAddr,
    ) -> Result<Self, HttpParseError> {
        let router = router.read().await;

        // params are created within the parse.
        let meta = {
            let mut stream_guard = stream.write().await;
            parser.parse(&mut stream_guard).await?
        };

        let mut route_variables = HashMap::new();
        let route = router
            .get_route(
                meta.clean_route(),
                meta.method().clone(),
                &mut route_variables,
            )
            .await?;

        let vars = Variables::new(route_variables);

        Ok(Self {
            socket,
            stream,
            variables: vars,
            meta,
            node: route,
        })
    }

    // Accessors generated by `immut_var!` / `immut_mut_var!`:
    //
    // * `socket(&self) -> &SocketAddr` — peer socket address of the
    //   connected client.
    // * `stream(&self) -> &Arc<RwLock<TcpStream>>` — shared handle to the
    //   underlying TCP stream.
    // * `node(&self) -> &Arc<RwLock<Node<'app>>>` — the router node that
    //   matched this request.
    // * `variables(&self) -> &Variables` / `variables_mut` — captured route
    //   parameters and user-set trace-line variables.
    // * `meta(&self) -> &HttpRequestMeta` / `meta_mut` — parsed request
    //   metadata (method, headers, route, body).
    immut_var!(socket, socket, SocketAddr);
    immut_var!(stream, stream, Arc<RwLock<TcpStream>>);
    immut_var!(node, node, Arc<RwLock<Node<'app>>>);

    immut_mut_var!(variables, variables_mut, variables, Variables);
    immut_mut_var!(meta, meta_mut, meta, HttpRequestMeta);
}
